import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${poppins.className} h-full flex flex-col`}
      >
        <Navbar />
        <Script
          src="https://kit.fontawesome.com/a2d5d067ac.js"
          crossOrigin="anonymous"
        ></Script>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
